logger_class:
  log_dir: "log/"
  system_log_file: "system.log"
  transaction_log_file: "transaxtion.log"

db_class:
  db_dir: "db/"
  monitoring_db_file: "Monitoring.db"
  stock_trade_db_file: "StockTrade.db"

stock_round_yaml:
  path: "src/config/stock_round_config.yaml"

